/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#735c00",
        "inverse-on-surface": "#f3f0ef",
        "surface": "#fcf9f8",
        "on-background": "#1c1b1b",
        "secondary-container": "#fed65b",
        "on-secondary-container": "#745c00",
        "secondary-fixed-dim": "#e9c349",
        "on-error": "#ffffff",
        "outline-variant": "#c8c7be",
        "surface-variant": "#e5e2e1",
        "error": "#ba1a1a",
        "surface-dim": "#dcd9d9",
        "surface-container": "#f0eded",
        "outline": "#787770",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e5e2dd",
        "on-primary": "#ffffff",
        "on-primary-container": "#6f6e6a",
        "on-secondary-fixed-variant": "#574500",
        "on-surface": "#1c1b1b",
        "tertiary-fixed": "#f3dedb",
        "on-surface-variant": "#474741",
        "tertiary-container": "#ffefed",
        "inverse-primary": "#c9c6c2",
        "tertiary": "#6a5b59",
        "tertiary-fixed-dim": "#d6c2bf",
        "on-tertiary-fixed-variant": "#514442",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#7a6b68",
        "inverse-surface": "#313030",
        "on-error-container": "#93000a",
        "background": "#fcf9f8",
        "on-secondary-fixed": "#241a00",
        "surface-container-highest": "#e5e2e1",
        "surface-tint": "#5f5e5b",
        "primary-fixed-dim": "#c9c6c2",
        "secondary-fixed": "#ffe088",
        "on-tertiary-fixed": "#241917",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf9f8",
        "on-primary-fixed": "#1c1c19",
        "on-primary-fixed-variant": "#474743",
        "on-secondary": "#ffffff",
        "primary-container": "#f5f2ed",
        "primary": "#5f5e5b",
        "surface-container-low": "#f6f3f2",
        "surface-container-high": "#eae7e7",
        "soft-blush": "#f8ecea",
        "onyx": "#1a1a1a",
        "gold": "#d4af37"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "unit": "8px",
        "section-gap": "120px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "headline-sm": ["Playfair Display"],
        "body-md": ["Montserrat"],
        "display-lg": ["Playfair Display"],
        "display-lg-mobile": ["Playfair Display"],
        "label-caps": ["Montserrat"]
      },
      fontSize: {
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.8", "letterSpacing": "0.01em", "fontWeight": "300" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.2em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
